[build]
target = "x86_64-pc-windows-msvc"
rustflags = ["-C", "target-cpu=native"]

[unstable]
build-std = ["alloc", "std", "panic_abort"]
build-std-features = ["compiler-builtins-mem", "panic_immediate_abort"] 
